name: Deploy Build Files Only

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 체크아웃 Develop 브랜치
        uses: actions/checkout@v2
        with:
          ref: develop
    
      - name: 프로젝트 빌드 및 빌드 파일 복사
        run: |
          set -e
          mkdir deploy
          cd rockpaperscissor_game
          npm install
          CI=false npm run build
          cd ..
          mkdir -p deploy/rockpaperscissor_game
          cp -R rockpaperscissor_game/build/* deploy/rockpaperscissor_game/
          cd shopping-site
          npm install
          CI=false npm run build
          cd ..
          mkdir -p deploy/shopping-site
          cp -R shopping-site/build/* deploy/shopping-site/
          cd weather-app
          npm install
          CI=false npm run build
          cd ..
          mkdir -p deploy/weather-app
          cp -R weather-app/build/* deploy/weather-app/

      - name: Main 브랜치 체크아웃
        uses: actions/checkout@v2
        with:
          ref: main
          persist-credentials: false

      - name: 빌드 파일 복사
        run: |
          git config user.name "yoora"
          git config user.email "yooralog@gmail.com"
          # 빌드 파일 복사
          shopt -s extglob
          rm -rf !(deploy|index.html)
          cp -R deploy/* ./
          rm -rf deploy
          git add .
          git commit -m "Deploy build files"
          git push origin main